const {test,expect}=require('@playwright/test');
const catalog=require('../lib/catalog').buildCatalog(require('../lib/load-catalog').loadCatalog(),{curated:true}).catalog;
const p=catalog.products.find(p=>p.kind==='cake'&&p.available&&!p.quoteOnly&&require('../lib/tier-options').tierCount(p,p.variants[0])===1),v=p.variants.find(v=>v.available);
async function seed(page){await page.goto('/');await page.evaluate(({p,v})=>localStorage.setItem('cake-cart-v1',JSON.stringify([{productId:p.id,variantId:v.id,quantity:2,personalisation:{colouring:'natural',allergens:'accept'}}])),{p,v});await page.goto('/checkout');}
test('carousels move with buttons and keyboard, support reduced motion and retain usable cards',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'});
 for(const width of [390,1440]){await page.setViewportSize({width,height:900});await page.goto('/');await page.evaluate(()=>document.fonts.ready);await expect(page.locator('.brand .brand-emblem,.footer-brand .brand-emblem')).toHaveCount(0);expect(await page.locator('.wordmark-name').first().evaluate(el=>getComputedStyle(el).fontFamily)).toContain('Runethia');for(const carousel of await page.locator('[data-carousel]').all()){const track=carousel.locator('[data-carousel-track]');await expect(carousel.locator('[data-carousel-prev]')).toBeDisabled();await carousel.locator('[data-carousel-next]').click();await expect.poll(()=>track.evaluate(el=>el.scrollLeft)).toBeGreaterThan(20);await track.focus();await track.press('End');await expect(carousel.locator('[data-carousel-next]')).toBeDisabled();await track.press('Home');await expect(carousel.locator('[data-carousel-prev]')).toBeDisabled();}expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();}
});
test('checkout switches regional delivery fees and pickup, validates billing and prepares a complete WhatsApp message',async({page})=>{
 await seed(page);await expect(page.locator('[data-delivery-fee]')).toContainText('AED 100');
 await page.locator('[name=emirate]').selectOption('Sharjah');await expect(page.locator('[data-delivery-fee]')).toContainText('AED 200');
 await page.locator('[name=fulfilment][value=pickup]').check();await expect(page.locator('[data-delivery-fee]')).toContainText('AED 0');await expect(page.locator('#shipping-fields')).toBeHidden();
 await page.locator('[name=fulfilment][value=delivery]').check();await expect(page.locator('[data-delivery-fee]')).toContainText('AED 200');
 await page.locator('[name=name]').fill('Aisha');await page.locator('[name=lastName]').fill('Test');await page.locator('[name=phone]').fill('+971500000000');await page.locator('[name=city]').fill('Sharjah');await page.locator('[name=area]').fill('Al Majaz');await page.locator('[name=address]').fill('Building 12, Apartment 4');await page.locator('[name=date]').fill('2099-12-01');
 await page.locator('[name=billingMode][value=different]').check();await expect(page.locator('[name=billingFirstName]')).toBeVisible();await expect(page.locator('[name=billingFirstName]')).toHaveJSProperty('required',true);
 for(const [name,value]of Object.entries({billingFirstName:'Sara',billingLastName:'Test',billingCity:'Dubai',billingArea:'Jumeirah',billingStreet:'Billing building 8'}))await page.locator('[name='+name+']').fill(value);
 await page.locator('[name=saveInfo]').check();await page.locator('[name=consent]').check();
 await page.screenshot({path:'artifacts/xavi-checkout-desktop.png',fullPage:true,animations:'disabled'});
 const pending=page.waitForResponse(r=>r.url().endsWith('/api/orders'));await page.locator('#submit-order').click();const response=await pending;expect(response.status()).toBe(201);const {order}=await response.json();expect(order.deliveryFeeFils).toBe(20000);expect(order.totalFils).toBe(v.priceFils*2+20000);expect(order.billingAddress.street).toBe('Billing building 8');expect(order.customer.shipping.area).toBe('Al Majaz');
 const link=page.locator('#send-whatsapp-order');await expect(link).toBeVisible();const url=new URL(await link.getAttribute('href'));expect(url.hostname).toBe('wa.me');const text=url.searchParams.get('text');expect(text).toContain('Delivery: AED 200');expect(text).toContain('Billing building 8');expect(text).toContain('Al Majaz');expect(text).toContain('Food colouring: Keep the natural cream colour');
 await page.goto('/checkout');await page.evaluate(({p,v})=>localStorage.setItem('cake-cart-v1',JSON.stringify([{productId:p.id,variantId:v.id,quantity:1,personalisation:{colouring:'natural',allergens:'accept'}}])),{p,v});await page.reload();await expect(page.locator('[name=name]')).toHaveValue('Aisha');await expect(page.locator('[name=area]')).toHaveValue('Al Majaz');await page.locator('[name=saveInfo]').uncheck();expect(await page.evaluate(()=>localStorage.getItem('xavi-checkout-profile-v1'))).toBeNull();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/xavi-checkout-mobile.png',fullPage:true,animations:'disabled'});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await expect(page.getByText('CCAvenue',{exact:false})).toHaveCount(0);
 for(const width of [320,768,1440]){await page.setViewportSize({width,height:900});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Populated checkout at '+width).toBeTruthy();}
});
