const { test, expect } = require('@playwright/test');
const catalog=require('../lib/load-catalog').loadCatalog();
const publicCatalog=require('../lib/catalog').buildCatalog(catalog,{curated:true});
const product=publicCatalog.byId.get(publicCatalog.catalog.featuredId);
const productURL='/cakes/'+product.handle;
async function screenshot(page,filename){
 await page.evaluate(()=>{document.querySelectorAll('img[loading=lazy]').forEach(img=>img.loading='eager');});
 await page.evaluate(()=>document.fonts.ready);
 await page.evaluate(()=>Promise.all([...document.images].map(img=>img.complete?Promise.resolve():new Promise(resolve=>{img.addEventListener('load',resolve,{once:true});img.addEventListener('error',resolve,{once:true});setTimeout(resolve,3000);}))));
 await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo({top:0,behavior:'instant'});});
 await page.screenshot({path:'artifacts/'+filename,fullPage:true,animations:'disabled'});
}
async function acknowledge(page){
 if(!await page.locator('[data-choice="preferences"]').evaluate(e=>e.open))await page.locator('[data-choice="preferences"] > summary').click();
 await page.locator('[name=colouring]').selectOption('natural');
 await page.locator('[name=allergens]').selectOption('accept');
}
test('luxury home, real navigation, and independent collection pages',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('/');
 await expect(page.locator('.wordmark-name').first()).toHaveText('ZAVI');
 await expect(page.locator('h1')).toContainText('Made to order');
 await expect(page.locator('#hero-image')).toBeVisible();
 await screenshot(page,'boutique-home-desktop.png');
 await page.locator('.desktop-nav summary').click();
 await expect(page.locator('.desktop-nav .mega-menu')).toBeVisible();
 await page.locator('.desktop-nav .mega-menu').getByRole('link',{name:'Wedding cakes',exact:true}).click();
 await expect(page).toHaveURL(/\/collections\/wedding-cakes$/);
 await expect(page.locator('h1')).toHaveText('Wedding cakes');
 await page.reload();
 await expect(page.locator('h1')).toHaveText('Wedding cakes');
 await page.goto('/collections');
 await expect(page.locator('.collection-tile')).toHaveCount(6);
 await expect(page.locator('h1')).toContainText('cake collections');
 expect(errors).toEqual([]);
});
test('collection price and flavour filters, pagination, and history work together',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});
 await page.goto('/collections/all');
 await expect(page.locator('.shop-results .product-card')).toHaveCount(12);
 await screenshot(page,'boutique-collection-desktop.png');
 await page.locator('[name=min]').fill('650');
 await page.locator('[name=max]').fill('900');
 await page.locator('.apply-price').click();
 await expect(page).toHaveURL(/min=650/);
 await expect(page.locator('.filter-chip')).toHaveCount(2);
 await page.locator('[name=flavour][value=chocolate]').check();
 await expect(page).toHaveURL(/flavour=chocolate/);
 await page.locator('[name=sort]').selectOption('price-desc');
 await expect(page).toHaveURL(/sort=price-desc/);
 const prices=await page.locator('.card-price').allTextContents();
 const values=prices.map(p=>Number(p.replace(/[^0-9.]/g,'')));
 expect(values.every(p=>p>=650&&p<=900)).toBeTruthy();
 expect(values).toEqual([...values].sort((a,b)=>b-a));
 await page.reload();
 await expect(page.locator('[name=flavour][value=chocolate]')).toBeChecked();
 await expect(page.locator('[name=min]')).toHaveValue('650');
 await page.locator('.filter-heading a').click();
 await expect(page).toHaveURL(/\/collections\/all$/);
 await page.locator('.pagination [aria-label="Next page"]').click();
 await expect(page).toHaveURL(/page=2/);
 await expect(page.locator('.pagination [aria-current]')).toHaveText('2');
 await page.goBack();
 await expect(page.locator('.pagination [aria-current]')).toHaveText('1');
 await page.locator('#filter-form [name=q]').fill('no-such-cake-xyz');
 await expect(page.locator('.empty-state')).toBeVisible();
});
test('reference product fields, exact variation pricing, saved cart, and order request',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(productURL);
 await expect(page.locator('h1')).toHaveText(product.title);
 await page.locator('[data-choice="preferences"] > summary').click();
 await expect(page.locator('[name=colouring]')).toBeVisible();
 await expect(page.locator('[name=allergens]')).toBeVisible();
 await expect(page.getByRole('link',{name:'Request design changes'})).toBeVisible();
 await page.getByRole('button',{name:'Enlarge product photo'}).click();
 await expect(page.locator('#product-lightbox')).toBeVisible();
 await page.keyboard.press('Escape');
 await expect(page.locator('#product-lightbox')).not.toBeVisible();
 await page.locator('[name=allergens]').selectOption('decline');
 await expect(page.locator('#add-to-cart')).toBeDisabled();
 await acknowledge(page);
 const option=page.locator('[data-option]').first();
 const choices=await option.locator('option').evaluateAll(options=>options.map(o=>o.value));
 await option.selectOption(choices[choices.length-1]);
 await expect(page).toHaveURL(/variant=/);
 const variantId=new URL(page.url()).searchParams.get('variant');
 const variant=product.variants.find(v=>v.id===variantId);
 await page.reload();
 const selected=await page.locator('[data-option]').evaluateAll(selects=>selects.map(s=>s.value));
 expect(selected).toEqual(variant.options);
 await acknowledge(page);
 await page.locator('[data-choice="details"] > summary').click();
 await page.locator('#cake-message').fill('Happy birthday, Sara!');
 await page.locator('[name=instructions]').fill('Gold initials, age 30');
 await screenshot(page,'boutique-product-desktop.png');
 await expect(page.locator('[data-product-quantity]')).toHaveCount(0);
 await page.locator('#add-to-cart').click();
 await expect(page.locator('#bag-drawer')).toBeVisible();
 await expect(page.locator('#bag-drawer .cart-item')).toContainText('Gold initials, age 30');
 await expect(page.locator('[data-bag-count]')).toHaveText('1');
 await page.reload();
 await expect(page.locator('[data-bag-count]')).toHaveText('1');
 await page.goto('/checkout');
  await page.locator('[name=name]').fill('Browser Test');
  await page.locator('[name=lastName]').fill('Customer');
  await page.locator('[name=city]').fill('Dubai');
  await page.locator('[name=area]').fill('Jumeirah');
 await page.locator('[name=phone]').fill('+971500000000');
 await page.locator('[name=email]').fill('test@example.com');
 await page.locator('[name=date]').fill('2099-12-01');
 await page.locator('[name=address]').fill('Test address, Dubai');
 await page.locator('[name=consent]').check();
 const responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/orders'));
 await page.locator('#submit-order').click();
 const response=await responsePromise;
 expect(response.status()).toBe(201);
 const {order}=await response.json();
 expect(order.subtotalFils).toBe(variant.priceFils);expect(order.items[0].quantity).toBe(1);
 expect(order.items[0].personalisation).toEqual({instructions:'Gold initials, age 30',colouring:'natural',allergens:'accept',tiers:[]});
 await expect(page.locator('#success-title')).toBeVisible();
 await expect(page.locator('[data-bag-count]')).toHaveText('0');
 const download=page.waitForEvent('download');await page.locator('#download-order').click();
 expect((await download).suggestedFilename()).toMatch(/^CAKE-/);
 expect(errors).toEqual([]);
});
test('wishlist persists across internal pages and supports removal',async({page})=>{
 await page.goto('/collections/all');
 await page.locator('.save-button').first().click();
 await page.goto('/wishlist');
 await expect(page.locator('#wishlist-content .product-card')).toHaveCount(1);
 await page.reload();
 await expect(page.locator('#wishlist-content .product-card')).toHaveCount(1);
 await page.locator('#wishlist-content .save-button').click();
 await expect(page.locator('#wishlist-content .empty-state')).toBeVisible();
});
test('mobile navigation, filters, product, and bag fit without horizontal overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.goto('/');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await screenshot(page,'boutique-home-mobile.png');
 await page.getByRole('button',{name:'Open menu'}).click();
 await expect(page.locator('#mobile-navigation')).toBeVisible();
 await page.locator('#mobile-navigation .mobile-cake-menu>summary').click();
 await page.locator('#mobile-navigation').getByRole('link',{name:'Shop all cakes',exact:true}).click();
 await expect(page).toHaveURL(/collections\/all$/);
 await page.locator('#toggle-filters').click();
 await expect(page.locator('#filters')).toBeVisible();
 await page.locator('[name=flavour][value=vanilla]').check();
 await expect(page).toHaveURL(/flavour=vanilla/);
 await expect(page.locator('#filters')).toBeVisible();
 await page.locator('#toggle-filters').click();
 await screenshot(page,'boutique-collection-mobile.png');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.goto(productURL);
 await acknowledge(page);
 await screenshot(page,'boutique-product-mobile.png');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
 await page.locator('#add-to-cart').click();
 await expect(page.locator('#bag-drawer')).toBeVisible();
 await page.locator('#bag-drawer .cart-remove').click();
 await expect(page.locator('#bag-drawer')).toContainText('Your cart is empty');
 await page.keyboard.press('Escape');
 await expect(page.locator('#bag-drawer')).not.toBeVisible();
});
test('bespoke and contact enquiries save independently with a downloadable brief',async({page})=>{
 await page.goto('/bespoke');
 await page.locator('[name=name]').fill('Bespoke Test');
 await page.locator('[name=email]').fill('bespoke@example.com');
 await page.locator('[name=phone]').fill('+971500000000');
 await page.locator('[name=occasion]').selectOption('Wedding');
 await page.locator('[name=date]').fill('2099-12-01');
 await page.locator('[name=guests]').fill('100');
 await page.locator('[name=budget]').selectOption('AED 2,000–4,000');
 await page.locator('[name=brief]').fill('Ivory tiers with burgundy ribbons.');
 await page.locator('[name=consent]').check();
 let responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/enquiries'));
 await page.locator('#enquiry-form button[type=submit]').click();
 let response=await responsePromise;
 expect(response.status()).toBe(201);
 expect((await response.json()).enquiry.kind).toBe('bespoke');
 await expect(page.locator('#enquiry-success-title')).toBeVisible();
 await expect(page.getByRole('link',{name:'Email your enquiry',exact:true})).toHaveAttribute('href',/^mailto:info@weddingcakes\.ae\?subject=/);
 await expect(page.locator('#enquiry-success').getByRole('link',{name:/Send your enquiry on WhatsApp/})).toHaveAttribute('href',/^https:\/\/wa.me\/971545974005\?text=/);
 const download=page.waitForEvent('download');await page.locator('#download-enquiry').click();
 expect((await download).suggestedFilename()).toMatch(/^CUSTOM-/);
 await page.goto('/contact');
 await page.locator('[name=name]').fill('Contact Test');
 await page.locator('[name=email]').fill('contact@example.com');
 await page.locator('[name=phone]').fill('+971500000000');
 await expect(page.locator('select[name=occasion]')).toHaveCount(0);
 await expect(page.locator('#enquiry-form')).not.toContainText('What can we help with?');
 await page.locator('[name=brief]').fill('Please advise about serving sizes.');
 await page.locator('[name=consent]').check();
 responsePromise=page.waitForResponse(r=>r.url().endsWith('/api/enquiries'));
 await page.locator('#enquiry-form button[type=submit]').click();
 response=await responsePromise;
 expect(response.status()).toBe(201);
 expect((await response.json()).enquiry).toMatchObject({kind:'contact',occasion:'General enquiry'});
 await expect(page.getByRole('link',{name:'Email your enquiry',exact:true})).toHaveAttribute('href',/^mailto:info@weddingcakes\.ae\?subject=/);
 await expect(page.locator('#enquiry-success-title')).toBeVisible();
});
test('internal pages render distinct server content and unknown pages return 404',async({page})=>{
 for(const [url,title]of [['/atelier','Maison Zavi'],['/delivery','Delivery & collection'],['/faq','Cake ordering'],['/privacy','Privacy policy'],['/collections/wedding-cakes','Wedding cakes'],['/collections/tiered-cakes','Tiered cakes']]){
  const response=await page.goto(url);expect(response.status()).toBe(200);await expect(page.locator('h1')).toContainText(title);
 }
 const response=await page.goto('/cakes/nonexistent-design');
 expect(response.status()).toBe(404);
 await expect(page.locator('h1')).toContainText('not found');
});
