'use strict';
const {shell,crumb,icon}=require('../lib/ui');
const {EMIRATES}=require('../lib/pricing');
const emirates=EMIRATES.map(e=>`<option>${e}</option>`).join('');
function checkout(ctx){
 const body=`<main id="main" class="wrap checkout-page">${crumb([['Your cart','/cart'],['Checkout']])}
 <header class="checkout-heading"><div><p class="eyebrow">REQUEST A QUOTE</p><h1>Delivery &amp; <em>contact details.</em></h1></div><p>Choose your delivery details.<br>Send your order to us on WhatsApp.</p></header>
 <section id="checkout-layout" class="checkout-layout"><form id="checkout-form">
 <fieldset class="checkout-step"><legend><span>01</span> Contact</legend><label>Email<input name="email" type="email" autocomplete="email" maxlength="160" required placeholder="you@example.com"></label><p class="field-help">Your order is discussed and confirmed on WhatsApp.</p><div class="form-grid"><label>First name<input name="name" autocomplete="given-name" maxlength="60" required></label><label>Last name<input name="lastName" autocomplete="family-name" maxlength="60" required></label></div><label>WhatsApp number<input name="phone" type="tel" autocomplete="tel" maxlength="30" placeholder="+971" required></label></fieldset>
 <fieldset class="checkout-step"><legend><span>02</span> Delivery</legend><p class="field-help">We deliver across the UAE. AED 100 in Dubai; AED 200 in all other emirates.</p><div class="fulfilment-options"><label><input type="radio" name="fulfilment" value="delivery" checked>Delivery <span>Across the UAE</span></label><label><input type="radio" name="fulfilment" value="pickup">Pickup <span>No delivery fee</span></label></div>
 <div id="shipping-fields"><label>Country<input value="United Arab Emirates" readonly autocomplete="shipping country-name"></label><div class="form-grid"><label>Emirate<select name="emirate" autocomplete="shipping address-level1">${emirates}</select></label><label>City<input name="city" autocomplete="shipping address-level2" maxlength="100" required></label></div><label>Area<input name="area" autocomplete="shipping address-level3" maxlength="120" placeholder="For example: Deira, Jumeirah, Bur Dubai" required></label><label>Street, apartment, building<textarea name="address" autocomplete="shipping street-address" maxlength="500" rows="2" required></textarea></label></div>
 <p id="pickup-note" class="checkout-callout" hidden>Pickup is free. We will confirm the collection location and time with you on WhatsApp.</p><div class="form-grid"><label>Preferred date<input type="date" name="date" required></label><label>Preferred time<select name="time" required><option value="10am-7pm">Between 10 am and 7 pm</option><option value="10am-10pm" data-pickup-time hidden disabled>Pickup: 10 am to 10 pm</option></select></label></div><label>Additional details <small>Optional</small><textarea name="notes" maxlength="1000" rows="3" placeholder="Delivery directions or other order details"></textarea></label><label class="consent"><input type="checkbox" name="saveInfo"><span>Save my contact and address in this browser for next time.</span></label><div class="delivery-method"><span id="delivery-method-label">Delivery across the UAE</span><strong id="delivery-method-price">AED 100</strong></div><p class="field-help">Your preferred date and time are confirmed on WhatsApp.</p></fieldset>
 <fieldset class="checkout-step"><legend><span>03</span> Billing address</legend><div class="billing-options"><label><input type="radio" name="billingMode" value="same" checked>Same as my delivery or contact details</label><label><input type="radio" name="billingMode" value="different">Use a different billing address</label></div><div id="billing-fields" hidden><label>Country<input value="United Arab Emirates" readonly></label><div class="form-grid"><label>First name<input name="billingFirstName" autocomplete="billing given-name" maxlength="60" disabled></label><label>Last name<input name="billingLastName" autocomplete="billing family-name" maxlength="60" disabled></label><label>Emirate<select name="billingEmirate" autocomplete="billing address-level1" disabled>${emirates}</select></label><label>City<input name="billingCity" autocomplete="billing address-level2" maxlength="100" disabled></label></div><label>Area<input name="billingArea" autocomplete="billing address-level3" maxlength="120" disabled></label><label>Street, apartment, building<textarea name="billingStreet" autocomplete="billing street-address" maxlength="500" rows="2" disabled></textarea></label><label>Phone <small>Optional</small><input name="billingPhone" type="tel" autocomplete="billing tel" maxlength="30" disabled></label></div></fieldset>
 <div class="whatsapp-checkout-note"><span class="eyebrow">CONFIRM YOUR ORDER</span><h2>Send your order on WhatsApp.</h2><p>Review your details, then send your order on WhatsApp. We will confirm your cake, availability and delivery with you there.</p></div><label class="consent"><input name="consent" type="checkbox" required><span>I agree to being contacted about my order. My cake and delivery date require confirmation. <a href="/privacy">Privacy information</a></span></label><p class="form-error" role="alert"></p><button class="button full-width" type="submit" id="submit-order">Prepare WhatsApp order ${icon('arrow')}</button><p class="form-footnote">Your order is confirmed with us on WhatsApp.</p></form><aside class="checkout-summary" id="checkout-summary"><p>Loading your cart…</p></aside></section><section id="order-success" class="order-success" hidden></section></main>`;
 return shell(ctx,{title:'Checkout',body,path:'/checkout',scripts:['checkout']});
}
module.exports={checkout};
