'use strict';
const {esc,img,link,crumb,shell}=require('../lib/ui');
const FAQ=[
 ['Choosing your cake',[['How do I choose a design?','Browse the collections by occasion or style. Use the price, flavour, size and availability filters to narrow your selection. Each design has its own page with the available variations.'],['Can I personalise a cake from the collection?','Select an available variation and add your cake message on the product page. For different colours, decorations or structural changes, use the custom cake enquiry form so the design can be discussed.'],['What if my preferred size is not listed?','Send a custom cake enquiry with your preferred design and approximate guest count. Sizes and prices outside the listed variations require an individual confirmation.']]],
 ['Ordering & payment',[['Does submitting a request confirm my order?','No. Prepare your order at checkout, then send the details to us on WhatsApp. Your order is confirmed with us there. Delivery is AED 100 in Dubai and AED 200 in all other emirates. Availability, your delivery date and payment arrangements still need confirmation.'],['Is payment taken on this website?','Orders are accepted through WhatsApp. No online payment options are offered. The request summary shows your cake subtotal, delivery fee and total. Payment arrangements are confirmed separately.'],['Can I save cakes for later?','Use the heart icon to add a design to your wishlist. Your wishlist and bag are saved in this browser, so they may not appear on a different device.']]],
 ['Delivery & care',[['Can I request a particular delivery date?','Yes. Add your preferred date and complete address when submitting your request. The date and delivery arrangements are subject to confirmation.'],['Are dietary requirements accommodated?','Recipes and ingredients vary. Include your requirements in the request and obtain confirmation before ordering. Please do not assume that a selected flavour is allergen-free.'],['How should I store my cake?','Ask for storage and serving instructions specific to your chosen recipe and decorations when your order is confirmed.']]]
];
function atelier(ctx){return require('./about').about(ctx);}
function information(ctx,type){
 const pages={
 delivery:{title:'Delivery & collection',eyebrow:'CLIENT CARE',intro:'Cake delivery across the UAE, with collection available by arrangement.',sections:[['Your preferred date','Cakes and personalised treats require preparation time and cannot be requested for same-day delivery. Large wedding installations need an individually agreed production and venue schedule. Add your requested date and full delivery address when you submit an order request. Your date is a preference until availability has been confirmed.'],['Delivery arrangements','We deliver across the UAE. Delivery costs AED 100 per order in Dubai and AED 200 in Abu Dhabi, Sharjah, Ajman, Umm Al Quwain, Ras Al Khaimah and Fujairah. Select your emirate at checkout to see your total. Delivery requests use a 10 am–7 pm window; an exact arrival time is not guaranteed. For large wedding installations, discuss access, assembly and venue requirements before confirming. Any additional setup service must be quoted and agreed separately; it is not added automatically at checkout.'],['Collection requests','Choose pickup in your cart for collection with no delivery fee. A collection location and time must be agreed before making travel arrangements.'],['Before the celebration','Review the confirmed design, flavours, message, date and address carefully. For changes, share your request as soon as possible; feasibility depends on the design and timing.']]},
 privacy:{title:'Privacy policy',eyebrow:'CLIENT CARE',intro:'How this website uses the information you choose to share.',sections:[['Your selection','Your wishlist and bag are stored in your browser. If you select Save my information at checkout, your contact and delivery address are also stored in this browser; uncheck it to remove that saved profile. They contain product references, quantities and cake messages. Removing your browser’s site data clears these saved items.'],['Order requests & enquiries','When you submit a request, your contact details and the information entered in the form are saved on the website server so the request can be reviewed. Optional reference images are saved privately with your custom cake enquiry. They are used to discuss your requested design. Payment card details are not collected by this website.'],['Contact handoff','If a bakery contact is configured and you choose the WhatsApp or email button, your request is passed to that application for you to send. Merely saving a request does not automatically send a message.'],['Images & external services','Product photos and fonts are served by this website. Opening WhatsApp or email uses the corresponding external service.'],['Sharing and purpose','Maison Zavi uses the details you submit to respond to enquiries, prepare requested orders and arrange fulfilment. Relevant order details may be shared with people providing the agreed delivery or cake service. The website does not include advertising trackers or send automated cart-reminder messages.'],['Keeping your information','Submitted requests and reference images remain in private server storage until removed by the operator. Maison Zavi should retain records only for the order, support and applicable record-keeping requirements. Contact us about access, correction or deletion; some records may need to be retained where the law requires.'],['Questions about your data','Use the contact page to ask Maison Zavi about information you have provided. Include your request reference when available. You can clear browser site data to remove saved selections and your optional checkout profile.']]},
 };
 const page=pages[type];
 const body='<main id="main" class="wrap">'+crumb([[page.title]])+'<section class="information-layout"><aside><p class="eyebrow">CLIENT CARE</p><nav aria-label="Client care"><a href="/delivery"'+(type==='delivery'?' aria-current="page"':'')+'>Delivery & collection</a><a href="/faq">Frequently asked questions</a><a href="/contact">Contact & enquiries</a><a href="/privacy"'+(type==='privacy'?' aria-current="page"':'')+'>Privacy</a></nav></aside><article><p class="eyebrow">'+page.eyebrow+'</p><h1>'+page.title+'</h1><p class="intro">'+page.intro+'</p>'+page.sections.map(([heading,text])=>'<section><h2>'+heading+'</h2><p>'+text+'</p></section>').join('')+link('/contact','Speak with us','button')+'</article></section></main>';
 return shell(ctx,{title:page.title,body,path:'/'+type});
}
function faq(ctx){
 const body='<main id="main" class="wrap">'+crumb([['Frequently asked questions']])+'<header class="page-intro"><p class="eyebrow">CLIENT CARE</p><h1>Cake ordering<br><em>questions.</em></h1></header><div class="faq-layout">'+FAQ.map(([group,items])=>'<section><h2>'+group+'</h2><div>'+items.map(([q,a])=>'<details><summary>'+q+'</summary><p>'+a+'</p></details>').join('')+'</div></section>').join('')+'</div><section class="editorial-cta"><h2>Something else<br><em>on your mind?</em></h2>'+link('/contact','Get in touch','button')+'</section></main>';
 return shell(ctx,{title:'Frequently asked questions',body,path:'/faq'});
}
function notFound(ctx){
 return shell(ctx,{title:'Page not found',path:'/404',body:'<main id="main" class="not-found wrap"><p class="eyebrow">404 · PAGE NOT FOUND</p><h1>Page<br><em>not found.</em></h1><p>This page could not be found. Browse the cakes or return to the homepage.</p>'+link('/collections/all','Explore the cakes','button')+link('/','Return home')+'</main>'});
}
module.exports={atelier,information,faq,notFound};

