'use strict';
const {esc,img,icon,link,crumb,shell}=require('../lib/ui');
function enquiry(ctx,isContact=false){
 const title=isContact?'Contact the maison':'Your custom cake';
 const whatsapp=require('../lib/contact').whatsappUrl(ctx.config);
 const whatsappLink=whatsapp?'<a href="'+esc(whatsapp)+'" target="_blank" rel="noopener"><span>WhatsApp <span dir="ltr">+971 54 597 4005</span></span>'+icon('arrow')+'</a>':'';
 const emailLink=ctx.config.email?'<a href="mailto:'+esc(ctx.config.email)+'"><span>Email <span>'+esc(ctx.config.email)+'</span></span>'+icon('arrow')+'</a>':'';
 const fieldset=(n,title,body)=>'<fieldset class="enquiry-fieldset"><legend><span>'+n+'</span>'+title+'</legend><div class="form-grid">'+body+'</div></fieldset>';
 const menu=items=>'<option value="">Please select</option>'+items.map(value=>'<option>'+esc(value)+'</option>').join('');
 const details=fieldset('01','Your details','<label>Your name<input name="name" autocomplete="name" maxlength="100" required placeholder="First and last name"></label><label>Email address<input name="email" type="email" autocomplete="email" maxlength="160" required placeholder="you@example.com"></label><label class="full-width">Phone number<input name="phone" type="tel" autocomplete="tel" placeholder="+971" maxlength="30" required></label>');
 const occasion=isContact?'<input type="hidden" name="occasion" value="General enquiry">':'<label class="full-width">The occasion<select name="occasion" required>'+menu(['Wedding','Engagement','Luxury celebration','Anniversary'])+'</select></label>';
 const event=!isContact?fieldset('02','Your occasion',occasion+'<label>Preferred date<input name="date" type="date" required></label><label>Approximate guests<input name="guests" type="number" min="1" max="99999" placeholder="e.g. 80" required></label><label class="full-width">Budget (AED)<select name="budget" required>'+menu(['Under AED 1,000','AED 1,000–2,000','AED 2,000–4,000','AED 4,000+','I would appreciate guidance'])+'</select></label>'):'';
 const upload=!isContact?'<div class="reference-upload full-width"><label for="reference-images">Inspiration images <small>Optional</small></label><p id="reference-help">Share up to 3 images, 5 MB each. JPG, PNG or WebP.</p><input id="reference-images" name="referenceFiles" type="file" accept="image/jpeg,image/png,image/webp" multiple aria-describedby="reference-help reference-error"><p id="reference-error" class="form-error" role="alert"></p><div id="reference-previews" aria-live="polite"></div></div>':'';
 const brief=fieldset(isContact?'02':'03',isContact?'Your enquiry':'Your inspiration',(isContact?occasion:'')+'<label class="full-width">'+(isContact?'Your message':'Tell us what you have in mind')+'<textarea name="brief" rows="4" maxlength="3000" placeholder="'+(isContact?'How can we help? For an existing order, include your reference.':'Colours, flowers, flavours and the details that matter to you.')+'" required></textarea></label>'+upload);
 const cake=ctx.bySlug.get('luxury-cakes')?.products.find(p=>p.id==='9920000000005')||ctx.catalog.products.find(p=>p.kind==='cake');
 const visual=cake?'<figure class="enquiry-visual"><img class="cake-image" src="'+esc(img(cake.image,500))+'" alt="'+esc(cake.imageAlt||cake.title)+'" width="125" height="150" loading="lazy"><figcaption><strong>Design and price confirmed before ordering.</strong>We’ll confirm the design, timing and quotation before your order.</figcaption></figure>':'';
 const body='<main id="main" class="enquiry-page wrap">'+crumb([[isContact?'Contact & enquiries':'Custom cakes']])+'<section class="enquiry-layout"><div class="enquiry-intro"><p class="eyebrow">'+(isContact?'CONTACT THE MAISON':'DESIGN YOUR OWN CAKE')+'</p><h1>'+(isContact?'Contact<br><em>Maison Zavi.</em>':'Request a<br><em>custom cake.</em>')+'</h1><p>'+(isContact?'A question about a cake, a delivery or an existing request? Tell us a little more and we’ll help with the details.':'Tell us your preferred cake size, flowers, colours and event date. Add reference photos if you have them.')+'</p><nav class="enquiry-help-links" aria-label="Enquiry help">'+emailLink+whatsappLink+(isContact?'<a href="/bespoke">Planning a custom cake? '+icon('arrow')+'</a>':'<a href="/collections">Browse designs for inspiration '+icon('arrow')+'</a>')+'<a href="/delivery">Delivery & collection '+icon('arrow')+'</a><a href="/faq">Frequently asked questions '+icon('arrow')+'</a></nav>'+visual+'</div><div class="enquiry-form-wrap"><p class="eyebrow">'+(isContact?'WE’RE HERE TO HELP':'LET’S BEGIN')+'</p><h2>'+(isContact?'Send us a note.':'Tell us your ideas.')+'</h2><p class="enquiry-form-intro">'+(isContact?'Share your details and message below.':'A few details will help us prepare your personal quotation.')+' All fields are required unless marked optional.</p><form id="enquiry-form" data-kind="'+(isContact?'contact':'bespoke')+'">'+details+event+brief+'<label class="consent"><input type="checkbox" name="consent" required><span>I agree to being contacted about this enquiry. <a href="/privacy">How we use your details</a></span></label><p class="form-error" role="alert"></p><button class="button full-width" type="submit">'+(isContact?'Send your enquiry':'Send your cake enquiry')+' '+icon('arrow')+'</button><p class="form-footnote">Submitting an enquiry does not confirm an order. We’ll confirm the design, price and date with you.</p></form><section id="enquiry-success" hidden></section></div></section></main>';
 return shell(ctx,{title,body,path:isContact?'/contact':'/bespoke',styles:['maison-pages'],scripts:['enquiry'],data:{enquiryKind:isContact?'contact':'bespoke'}});
}
function bag(ctx,path='/cart'){return require('./cart').cart(ctx,path);}
function wishlist(ctx){
 return shell(ctx,{title:'Your wishlist',path:'/wishlist',scripts:['wishlist'],body:'<main id="main" class="wrap">'+crumb([['Your wishlist']])+'<header class="page-intro compact"><p class="eyebrow">KEPT FOR ANOTHER LOOK</p><h1>Your <em>wishlist.</em></h1><p>Cakes you’ve saved for later.</p></header><section id="wishlist-content" class="wishlist-content"><p>Loading your saved designs…</p></section></main>'});
}
function checkout(ctx){return require('./checkout').checkout(ctx);}
module.exports={enquiry,bag,wishlist,checkout};

