from pathlib import Path
def edit(file,old,new):
    p=Path(file);s=p.read_text(encoding='utf-8')
    if old not in s: raise RuntimeError(file+' missing '+old[:70])
    p.write_text(s.replace(old,new),encoding='utf-8')
edit('lib/ui.js',"const varies=p.listingMaxFils", "const varies=p.priceOnConsultation||p.listingMaxFils")
# Keep ternary precedence explicit for consultation prices.
edit('lib/ui.js',"const varies=p.priceOnConsultation||p.listingMaxFils!==undefined?p.listingMaxFils>min:new Set(p.variants.filter(v=>v.available).map(v=>v.priceFils)).size>1;", "const varies=p.priceOnConsultation||(p.listingMaxFils!==undefined?p.listingMaxFils>min:new Set(p.variants.filter(v=>v.available).map(v=>v.priceFils)).size>1);")
edit('lib/ui.js',"esc(p.title)+'\" width=\"700\"", "esc(p.imageAlt||p.title)+'\" width=\"700\"")
edit('lib/ui.js',"navLink('/privacy','Privacy')", "navLink('/privacy','Privacy policy')")
edit('lib/ui.js',"navLink('/cart','Your cart')+'</div></div><div class=\"footer-bottom wrap\">", "navLink('/cart','Your cart')+'</div></div><nav class=\"footer-policies wrap\" aria-label=\"Policies\">'+navLink('/delivery','Shipping & delivery')+navLink('/policies/refund-policy','Refunds & cancellations')+navLink('/policies/substitution-policy','Substitution policy')+navLink('/privacy','Privacy policy')+navLink('/policies/terms-of-service','Terms & conditions')+navLink('/policies/edible-items-policy','Edible items & cake care')+'</nav><div class=\"footer-bottom wrap\">")
edit('pages/product.js',"money(selected.priceFils)+'</p><p class=\"product-intro\">", "(p.priceOnConsultation?'From ':'')+money(selected.priceFils)+'</p>'+(p.priceOnConsultation?'<div class=\"design-specification\"><p>'+esc(p.specification)+'</p><dl><div><dt>Flowers</dt><dd>'+esc(p.flowers)+'</dd></div><div><dt>Finish</dt><dd>'+esc(p.finish)+'</dd></div></dl><p>Starting design estimate. Guest count, dimensions, edible tiers, flower materials and venue setup are confirmed in your personal quotation before you order.</p></div>':'')+'<p class=\"product-intro\">")
edit('pages/product.js',"esc(p.title)+'\" width=\"1100\"", "esc(p.imageAlt||p.title)+'\" width=\"1100\"")
edit('pages/product.js',"'<div class=\"photo-note\">", "(p.imageNote?'<p class=\"image-reference-note\">'+esc(p.imageNote)+'</p>':'')+'<div class=\"photo-note\">")
edit('assets/js/product.js',"$('#product-price').textContent=money(selected.priceFils);", "$('#product-price').textContent=(product.priceOnConsultation?'From ':'')+money(selected.priceFils);")
edit('pages/home-content.js',"const wedding=ctx.byId.get('8028661612769');", "const wedding=ctx.byId.get('9900000000003');")
edit('pages/home-content.js',"['8028660203745','8028660531425','8028656042209','8028661514465','8028660564193','8028655780065']", "['9900000000001','9900000000002','9900000000003','9900000000004','9900000000005','9900000000006']")
edit('pages/home-content.js','/assets/brand/wedding-hero.png','/assets/studio/grand-floral-palace.png')
edit('pages/home-content.js','An ivory floral wedding cake in a candlelit reception setting','Design concept for a grand floral wedding cake installation with three ivory cake towers')
edit('pages/home-content.js','home-hero cinematic-hero','home-hero cinematic-hero floral-hero')
edit('pages/home-content.js','A few to fall in love with','Grand floral wedding designs')
edit('pages/home-content.js','Soft florals, sculpted tiers and the details that make it yours. Find a wedding cake as memorable as the day itself.','Six statement floral concepts, from six-tier orchids to a complete cake installation. Starting design estimates from AED 100,000 to AED 500,000, with every detail agreed in your personal consultation.')
edit('pages/home-content.js','[p[0],p[1],p[2],p[4],p[5],p[8]]','[p[6],p[7],p[8],p[10],p[11],p[14]]')
edit('pages/home.js',"ctx.byId.get('8028661612769')", "ctx.byId.get('9900000000003')")
edit('pages/home.js',"ctx.catalog.products[curated[c.slug]]", "ctx.catalog.products.filter(p=>!p.priceOnConsultation)[curated[c.slug]]")
edit('server.js','unitPriceFils:v.priceFils,lineTotalFils:', 'priceOnConsultation:!!p.priceOnConsultation,unitPriceFils:v.priceFils,lineTotalFils:')
edit('server.js','return send(200,{items,...totals(', 'return send(200,{items,hasStartingPrices:items.some(i=>i.priceOnConsultation),...totals(')
edit('lib/orders.js','variation: variant.title, quantity:', 'priceOnConsultation:!!product.priceOnConsultation,variation: variant.title, quantity:')
edit('lib/orders.js',"currency: 'AED', items,", "currency: 'AED', hasStartingPrices:items.some(i=>i.priceOnConsultation),items,")
edit('assets/js/app.js',"'Subtotal: '+money(order.subtotalFils)","...(order.hasStartingPrices?['STARTING ESTIMATE — final design, scale and price require written confirmation.']:[]),'Subtotal: '+money(order.subtotalFils)")
edit('assets/js/checkout.js','${quote.items.map(item=>', '${quote.hasStartingPrices?\'<p class="starting-price-note">Starting design estimate. Final specifications and the complete quotation must be agreed on WhatsApp before ordering.</p>\':\'\'}${quote.items.map(item=>')
edit('assets/js/checkout.js','${esc(order.id)}</p><div class="fee-row">','${esc(order.id)}</p>${order.hasStartingPrices?\'<p class="starting-price-note">Starting estimate only. Final design and quotation require confirmation.</p>\':\'\'}<div class="fee-row">')
