from pathlib import Path
def edit(file,old,new):
 p=Path(file);s=p.read_text(encoding='utf-8')
 if old not in s:raise RuntimeError(file+' '+old[:70])
 p.write_text(s.replace(old,new),encoding='utf-8')
edit('pages/product.js',"body,path:'/cakes/'+p.handle,scripts:","body,path:'/cakes/'+p.handle,noindex:!!p.imageReference,scripts:")
edit('pages/editorial.js',"privacy:{title:'Privacy & your details'", "privacy:{title:'Privacy policy'")
edit('pages/editorial.js',"['Questions about your data','Use the contact page to submit a request about information you have provided. Include the request reference when available.']", "['Sharing and purpose','Maison Xavi uses the details you submit to respond to enquiries, prepare requested orders and arrange fulfilment. Relevant order details may be shared with people providing the agreed delivery or cake service. The website does not include advertising trackers or send automated cart-reminder messages.'],['Keeping your information','Submitted requests and reference images remain in private server storage until removed by the operator. Maison Xavi should retain records only for the order, support and applicable record-keeping requirements. Contact us about access, correction or deletion; some records may need to be retained where the law requires.'],['Questions about your data','Use the contact page to ask Maison Xavi about information you have provided. Include your request reference when available. You can clear browser site data to remove saved selections and your optional checkout profile.']")
edit('pages/editorial.js',"['Your preferred date','Add your requested date", "['Your preferred date','Cakes and personalised treats require preparation time and cannot be requested for same-day delivery. Large wedding installations need an individually agreed production and venue schedule. Add your requested date")
edit('pages/editorial.js',"Delivery dates and time windows require confirmation.", "Delivery requests use a 10 am–7 pm window; an exact arrival time is not guaranteed. For large wedding installations, discuss access, assembly and venue requirements before confirming. Any additional setup service must be quoted and agreed separately; it is not added automatically at checkout.")
edit('tests/category-profiles.test.js',"assert.equal(ctx.byId.get('8028660203745').image,'assets/products/white-blush-wedding-enhanced.png');", "assert.ok(ctx.byId.get('8028660203745').image.startsWith('assets/studio/'));assert.equal(ctx.byId.get('8028660203745').imageReference,true);")
